### PR TITLE
fix(mission) try to fix ConcurrentModificationException !

### PR DESCRIPTION
**Pull request by NewZAZ**
Add iterator for fix ConcurrentModificationException

### CODE REVIEW

**Comment by NewZAZ** [comment]
[#](https://github.com/BG-Software-LLC/SuperiorSkyblock2/issues/1450)

**Comment by OmerBenGera** [comment]
The error happens because saveMissions is done async while saving data is done sync.
I dont think changing this to an iterator will have any effect on the error.

**Comment by OmerBenGera** [comment]
The error happens because saveMissions is done async while saving data is done sync.
I dont think changing this to an iterator will have any effect on the error.

**Comment by NewZAZ** [comment]
https://stackoverflow.com/questions/5847939/is-list-iterator-thread-safe

Iterator is thread safe and cannot get ConcurrentModificationException

**Comment by OmerBenGera** [comment]
> https://stackoverflow.com/questions/5847939/is-list-iterator-thread-safe
> 
> Iterator is thread safe and cannot get ConcurrentModificationException

The concurrent modification is not because of this iteration.
The issue is that the missions modify the data while its being saved, causing the error to occur (from what Ive seen at least)
This is a fault of the way I designed the missions. I will need somehow to fix it without breaking the missions.
Still thinking about a way to do it.

**Comment by NewZAZ** [comment]
Ok my bad.

**Comment by iamnoksio** [comment]
> > https://stackoverflow.com/questions/5847939/is-list-iterator-thread-safe
> > Iterator is thread safe and cannot get ConcurrentModificationException
> 
> The concurrent modification is not because of this iteration. The issue is that the missions modify the data while its being saved, causing the error to occur (from what Ive seen at least) This is a fault of the way I designed the missions. I will need somehow to fix it without breaking the missions. Still thinking about a way to do it.

You literally just need to put a ConcurrentHashMap LMAO

**Comment by OmerBenGera** [comment]
> > > https://stackoverflow.com/questions/5847939/is-list-iterator-thread-safe
> > > Iterator is thread safe and cannot get ConcurrentModificationException
> > 
> > 
> > The concurrent modification is not because of this iteration. The issue is that the missions modify the data while its being saved, causing the error to occur (from what Ive seen at least) This is a fault of the way I designed the missions. I will need somehow to fix it without breaking the missions. Still thinking about a way to do it.
> 
> You literally just need to put a ConcurrentHashMap LMAO
> 
> EDIT: getAllMission > missionMap = ConcurrentHashMap

As I said, this will not fix the issue.
The missions map is not changed during a session, and the error comes from modifing values in mission data holders.
When saving tracked data, the mission jars iterates through the data and save it. However, if in that time they also try to track data, it will throw the error.
Setting the map to a ConcurrentHashMap most of the time fix the issue, however thats not the case here.

**Comment by iamnoksio** [comment]
you just dont know how to dev correctly dude

**Pull request closed without merging**
