### PR TITLE
Do not force all players on different islands to sleep at the same ti…

### PR DESCRIPTION
**Pull request by jfoucher**
Do not force all players on different islands to sleep at the same time. Fixes https://github.com/BG-Software-LLC/SuperiorSkyblock2/issues/2008

### CODE REVIEW

**Comment by jfoucher** [comment]
@OmerBenGera Let me know if you'd like me to do something differently, or maybe add a config option for this.

**Comment by OmerBenGera** [comment]
This will force daylight to the entire world, not only to the sleeping island.
This is not the best solution tbh, and in general making such thing is not gonna be easy.

Why not making a module to do that instead?

**Comment by jfoucher** [comment]
Yeah you're right that this is a problem, but I could not find another way to make it work. Since the time is by world, each island should be it's won world for one to be at night and the other day, so indeed I don't think there is a proper solution to this problem. I use this PR on my server and, well for some players it will become day suddenly if players on another island went to bed,  but it is a compromise they are willing to accept.

**Comment by OmerBenGera** [comment]
> Yeah you're right that this is a problem, but I could not find another way to make it work. Since the time is by world, each island should be it's won world for one to be at night and the other day, so indeed I don't think there is a proper solution to this problem. I use this PR on my server and, well for some players it will become day suddenly if players on another island went to bed, but it is a compromise they are willing to accept. I did not know it was possible to make modules for SuperiorSkyblock, I'll look into it.

Because some may don't want it, I prefer if you had it as a separate module.
I am closing this for now, thanks however for the contribution!

**Pull request closed without merging**
