### PR TITLE
Translation in german

### PR DESCRIPTION
**Pull request by CraftCityHD**
I have translated the en-US into German

### CODE REVIEW

**Comment by OmerBenGera** [comment]
Do you know how to switch branches?
I need you to make the pull-request into the `dev` branch, not `master`

**Comment by CraftCityHD** [comment]
no. did it again there. If that's wrong too, I'd better leave it.
[https://github.com/BG-Software-LLC/SuperiorSkyblock2/pull/814]

**Comment by OmerBenGera** [comment]
I'll do it, no worries.
Thanks for the contribution!

**Comment by OmerBenGera** [comment]
Accepted (I created my own branch and merged it already)

**Pull request closed without merging**
